### ISSUE TITLE
Non-resolvable parent POM for vcat

### ISSUE THREAD

**Issue by vb078** [dapete42/vcat#1]
Hello

I try to install vcat with Maven...
I run it from the root (of the reportery)

I have this error

> Non-resolvable parent POM for vcat:vcat-core:[unknown-version]: Could not find artifact vcat:vcat:pom:2-SNAPSHOT

And find a lot of poeple with the same problem...
[https://forums.manning.com/posts/list/32058.page;jsessionid=77A500E7473CA53D1BDEC104B8AF4292#p60634](https://forums.manning.com/posts/list/32058.page;jsessionid=77A500E7473CA53D1BDEC104B8AF4292#p60634)

Do you have any solution ?
I use Apache Maven 3.3.9 (and TomCat is installed too)

Thank you.

**Comment by dapete42** [comment]
Sorry I didn't see this earlier, I was not expecting anyone to open issues for this, and had no notifications set up. The problem is fixed.

I had updated the version to 3-SNAPSHOT on the root project, but forgotten to also do it for the submodules. I have done this now and can successfully run 'mvn install' on a clean system (a fresh Ubuntu using the same Maven version you used).
